/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/join` | `/join`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/lobby` | `/lobby`; params?: Router.UnknownInputParams; } | { pathname: `/game/round`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/join` | `/join`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/lobby` | `/lobby`; params?: Router.UnknownOutputParams; } | { pathname: `/game/round`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/join${`?${string}` | `#${string}` | ''}` | `/join${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/lobby${`?${string}` | `#${string}` | ''}` | `/lobby${`?${string}` | `#${string}` | ''}` | `/game/round${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/join` | `/join`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/lobby` | `/lobby`; params?: Router.UnknownInputParams; } | { pathname: `/game/round`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
