/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dev`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/answer-phase` | `/answer-phase`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/join` | `/join`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/leaderboard` | `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/lobby` | `/lobby`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/qm-active` | `/qm-active`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/round-results` | `/round-results`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/round-start` | `/round-start`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/waiting` | `/waiting`; params?: Router.UnknownInputParams; } | { pathname: `/game/round`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/dev`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/answer-phase` | `/answer-phase`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/create` | `/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/join` | `/join`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/leaderboard` | `/leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/lobby` | `/lobby`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/qm-active` | `/qm-active`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/round-results` | `/round-results`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/round-start` | `/round-start`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(game)'}/waiting` | `/waiting`; params?: Router.UnknownOutputParams; } | { pathname: `/game/round`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/dev${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/answer-phase${`?${string}` | `#${string}` | ''}` | `/answer-phase${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/create${`?${string}` | `#${string}` | ''}` | `/create${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/join${`?${string}` | `#${string}` | ''}` | `/join${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/leaderboard${`?${string}` | `#${string}` | ''}` | `/leaderboard${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/lobby${`?${string}` | `#${string}` | ''}` | `/lobby${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/qm-active${`?${string}` | `#${string}` | ''}` | `/qm-active${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/round-results${`?${string}` | `#${string}` | ''}` | `/round-results${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/round-start${`?${string}` | `#${string}` | ''}` | `/round-start${`?${string}` | `#${string}` | ''}` | `${'/(game)'}/waiting${`?${string}` | `#${string}` | ''}` | `/waiting${`?${string}` | `#${string}` | ''}` | `/game/round${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dev`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/answer-phase` | `/answer-phase`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/create` | `/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/join` | `/join`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/leaderboard` | `/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/lobby` | `/lobby`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/qm-active` | `/qm-active`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/round-results` | `/round-results`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/round-start` | `/round-start`; params?: Router.UnknownInputParams; } | { pathname: `${'/(game)'}/waiting` | `/waiting`; params?: Router.UnknownInputParams; } | { pathname: `/game/round`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
